---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-admin-binding
roleRef:
  kind: ClusterRole
  name: cluster-admin # default cluster role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: my-admin # our own admin group created by us
    apiGroup: rbac.authorization.k8s.io